#!/usr/bin/python3
# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# This script is designed to be safe: it reads existing data from publications_map.json and produces a lib/publications_generated.tex file
# for those publications that should be included in a compilation thesis (as attached publications).
# 
import json
import os

MAP_FILE = 'publications_map.json'
OUTPUT_FILE = 'lib/publications_generated.tex'

# Mapping of label prefixes to the LaTeX environments
ENV_MAP = {
    'paper': 'ListOfPapers',
    'patent': 'ListOfPatents',
    'artifact': 'ListOfArtifacts',
    'poster': 'ListOfPosters',
    'patentapplication': 'ListOfPatentApplications',
    'report': 'ListOfReports',
    'dataset': 'ListOfDatasets'
}

def generate_latex():
    if not os.path.exists(MAP_FILE):
        print(f"Error: {MAP_FILE} not found.")
        return

    with open(MAP_FILE, 'r', encoding='utf-8') as f:
        pub_map = json.load(f)

    # Filter and group entries
    grouped_entries = {env: [] for env in ENV_MAP.values()}
    
    for diva_id, data in pub_map.items():
        if data.get('status') == 'included' and data.get('label'):
            # Split 'paper:A' into ('paper', 'A')
            try:
                prefix, identifier = data['label'].split(':')
                env_name = ENV_MAP.get(prefix)
                if env_name:
                    grouped_entries[env_name].append({
                        'id': identifier,
                        'title': data['title'],
                        'bib_key': data['bib_key'],
                        'prefix': prefix
                    })
            except ValueError:
                print(f"Warning: Invalid label format for {diva_id}: {data['label']}")

    # Build the LaTeX string
    latex_output = ["% --- Generated by DiVA_generator.py ---", ""]

    for env_name in ENV_MAP.values():
        entries = grouped_entries[env_name]
        if not entries:
            continue
        
        # Sort by the identifier (A, B, C...)
        entries.sort(key=lambda x: x['id'])
        
        latex_output.append(f"\\begin{{{env_name}}}")
        for entry in entries:
            # Use the prefix as the label type (paper, patent, etc.)
            label_cmd = f"\\label{{{entry['prefix']}:{entry['id']}}}"
            item = f"  \\item {label_cmd} {entry['title']} \\cite{{{entry['bib_key']}}}"
            latex_output.append(item)
        latex_output.append(f"\\end{{{env_name}}}")
        latex_output.append("") # Blank line between environments

    # Ensure the directory exists
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(latex_output))
    
    print(f"Successfully generated {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_latex()
